on:
  repository_dispatch:
    types: [docs-deployed]
  workflow_dispatch:

jobs:
  scrape:
    runs-on: self-hosted
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v3

        - name: Run DocSearch Scraper
          uses: celsiusnarhwal/typesense-scraper@v2
          with:
            api-key: ${{ secrets.TYPESENSE_API_KEY }}

            host: typesense-ry11skxh00f1o88f1hsvpt4p

            port: 8108

            protocol: http

            config: typesense/docsearch.config.json
