on:
  repository_dispatch:
    types: [docs-deployed]
  workflow_dispatch:

jobs:
  scrape:
    runs-on: self-hosted
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v3

        - name: Run DocSearch Scraper
          uses: celsiusnarhwal/typesense-scraper@v2
          with:
            api-key: ${{ secrets.TYPESENSE_API_KEY }}

            # The hostname or IP address of your Typesense server. Required.
            host: typesense.moritz-grimm.dev

            port: 8108

            protocol: https

            config: typesense/docsearch.config.json
